#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs
apt update && apt install -y nginx
sed -i 's/# listen 80;/listen 80;/g' /etc/nginx/sites-available/default
systemctl restart nginx
